### ISSUE TITLE
获取文件列表可能不需要 OAuth Apps 

### ISSUE THREAD

**Issue by rwv** [Ghosin/jsdelivr_clone#1]
Have a look at [https://developer.github.com/v3/git/trees/#get-a-tree-recursively](https://developer.github.com/v3/git/trees/#get-a-tree-recursively)?
Example API call: [https://api.github.com/repos/FFmpeg/FFmpeg/git/trees/772dfbabf1f1817660216a6ece8458be0ad26bfd?recursive=1](https://api.github.com/repos/FFmpeg/FFmpeg/git/trees/772dfbabf1f1817660216a6ece8458be0ad26bfd?recursive=1)

**Comment by Ghosin** [comment]
If you do not use OAuth, the API call speed limit may cause the script to be unavailable. https://developer.github.com/v3/#rate-limiting
